export const AdminMenu=[
    {
        path:'user',
        data:{
            menu:{
                id:1,
                title:'用户管理',
                icon:'fa-university',
                selected:false,
                expanded:false,
                order:0
            }
        }
    },
    {
        path:'role',
        data:{
            menu:{
                id:2,
                title:'角色管理',
                icon:'fa-address-card',
                selected:false,
                expanded:false,
                order:0
            }
        }
    },
    {
        path:'power',
        data:{
            menu:{
                id:3,
                title:'权限管理',
                icon:'fa-users',
                selected:false,
                expanded:false,
                order:0
            }
        }
    },
    {
        path:'card',
        data:{
            menu:{
                id:4,
                title:'房卡管理',
                icon:'fa-cogs',
                selected:false,
                expanded:false,
                order:0
            }
        }
    },
    {
        path:'cardLog',
        data:{
            menu:{
                id:8,
                title:'房卡日志',
                icon:'fa-cogs',
                selected:false,
                expanded:false,
                order:0
            }
        }
    },
    {
        path:'player',
        data:{
            menu:{
                id:5,
                title:'玩家管理',
                icon:'fa-history',
                selected:false,
                expanded:false,
                order:0
            }
        }
    },
    {
        path:'system',
        data:{
            menu:{
                id:6,
                title:'系统管理',
                icon:'fa-history',
                selected:false,
                expanded:false,
                order:0
            }
        }
    },
    {
        path:'systemLog',
        data:{
            menu:{
                id:7,
                title:'日志管理',
                icon:'fa-history',
                selected:false,
                expanded:false,
                order:0
            }
        }
    }
    
]